{% set version = "2.9" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sampling
  version: {{ version|replace("-", "_") }}

source:
  fn: sampling_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sampling_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sampling/sampling_{{ version }}.tar.gz
  sha256: 7f5ba5978f6cdbbbdb6f51958197b28b6fc63e7eeee59e6845ea09fb37d1b187

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-lpsolve

  run:
    - r-base
    - r-mass
    - r-lpsolve

test:
  commands:
    - $R -e "library('sampling')"  # [not win]
    - "\"%R%\" -e \"library('sampling')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sampling
  license: GPL (>= 2)
  summary: Functions for drawing and calibrating samples.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
