{% set version = "2.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sampling
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sampling_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sampling/sampling_{{ version }}.tar.gz
  sha256: 7f5ba5978f6cdbbbdb6f51958197b28b6fc63e7eeee59e6845ea09fb37d1b187

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-lpsolve
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-lpsolve

test:
  commands:
    - $R -e "library('sampling')"           # [not win]
    - "\"%R%\" -e \"library('sampling')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sampling
  license: GPL-2.0-or-later
  summary: Functions for drawing and calibrating samples.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
