appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: V2Map/6gEhCj1JMnZwbVOwuyGWD2ZDgJkzsgGmODDh5iklFnnmPvhtY5vjHru+5yXckUT/CzkbPtr2UEMAckysAvN7Cd/2Naw4efeEfHEfkRd8qrlDgOIoUUGToYlhdnvSAgFFkmyKJODZNqHXSlm0Yims4J6/coUQeYwU8O9tiDC9E+97C/St9LWc+6JSSEON1Tbj0simdg5OM2JM0wM6I3R8uAAotw+TGfHnq1Lmxj52vPc5Nac2WmCKla9IBo71oLURgb9CitpfetQa0M9EQSxsBnl5haCe8DgGdyhQBv/Lvrv+2SW5XXq/p26cId+5yHhoNLFBOs4YVy9nzQdfoZ3M53vn2XcxayQTkX9AJvoIgYbGQvKQjj8t1kwPbKTPv7Fzep4O1a9Hurcn2N4fA9Cie00vhuEHVXsIR47ad3L+CqvP4u1HBSXbS9YSxa+/5ds9qhxFeJ1gyPIT0dWZAoLkZvNNTTIMHIjbpUw2xM77mdSI/v+uWMZ9TKisC+YqyqShMsVcd7KFCemUpPAlMaN9RrtoCpMOG9+fIQLnhGmBd7awJjxzJDNTVKmS+qBhxfzyV1kEsu21tNdGM9eJX1z9ChTygJ3sEGKrRHuPYuN+YiR2LGiZUxpHQTdD2KorK9ohbClearX56w3qrkLVcYYseHeAydhRWOvkM3uAU=}
