travis:
  secure:
    BINSTAR_TOKEN: O+4oaJ8PaL6RGrduFJ/0vtT0ACvWsJfPM+ATevNmluluEkzvDFq1+oewdjk+9C4kOw11X6t8F33fNlzLzFZapL9BU1TgG/ocMMWWf4LEAhbFHXboDk1U6WEDITgsrwXm6YG/J795fk9KVYmrdUgsPT3xQXhQ2JetXpX7S6CvWBDnHOCCz4ZFwMWeI6aUWEX2ZrlfaPiYmgH/v/d5qgqsA2KVpKhrJa/7kI32JMSjED+nXRdIOtKQcqXG8aMEMcY2RIsqDZqO7lBWfiCEa1JOVqDJOB7KIsE2HnGGmEKAAHzjMaN5oIvVeAl8uV64CbSL1RjHPyBlQf8H0Q0eGe4aZ02HTC5BEc6S6YDkhmSu9EO9OXvgLg59mCEUiiqTnU0whVul0USrIJUuwiXwkLJiVbXFCgqVITtnPfJfeQ5RUMCaD/DqMQ0A04+2t5m6Pe99M35XiNq/tfD9KmDP5No0aTLJLobSt/a4ONBzepYeTEHEPZTuSfJ2IYEFn/Lu+Qn/lp+6B+6TG7Y/NFDOSmz/61kwpNtqgqNrslYkFu/6dhlxuC1Q5N3yvwFgsW4LkM7TBcG0mrijm9OhcpDFSvPYlH460QwIV6fVVwKrknynwbfZSqcQZ6s5DF37m0x7QdvDmbWKinyxLD7Mx2CneAqpj6VsCCqZguoKXDQk7u5TLuU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
